#!/usr/bin/env python3
"""Canonical fast repository validation. Installer tests live in test_installers.py."""

from __future__ import annotations

import re
import shutil
import sys
import tempfile
import tomllib
import urllib.parse
from pathlib import Path

import generate_agents


ROOT = Path(__file__).resolve().parents[1]
SKILLS = ROOT / "skills"
TEXT_SUFFIXES = {".md", ".yaml", ".yml", ".json", ".py", ".sh", ".ps1", ".toml"}
RETIRED_BUCKETS = {"engineering", "productivity", "misc", "deprecated", "in-progress"}
RETIRED_FILES = {
    "CLAUDE.md",
    "CHANGELOG.md",
    "package.json",
    "package-lock.json",
    ".github/workflows/release.yml",
    "scripts/sync-plugin-version.mjs",
    "scripts/link-skills.sh",
}
STALE_PATTERNS = {
    "ask-matt": re.compile(r"ask-matt", re.IGNORECASE),
    "old setup skill": re.compile(r"setup-matt-pocock-skills", re.IGNORECASE),
    "bucketed skill path": re.compile(r"skills/(?:engineering|productivity|misc|deprecated|in-progress)/", re.IGNORECASE),
    "mirrored docs path": re.compile(r"docs/(?:engineering|productivity)/", re.IGNORECASE),
    "Claude plugin manifest": re.compile(r"\.claude-plugin|claude plugins? install", re.IGNORECASE),
    "old publishing URL": re.compile(r"aihero\.dev", re.IGNORECASE),
}
INTENTIONAL_STALE_REFERENCE_FILES = {"install.sh", "install.ps1", "scripts/check.py"}
STANDALONE_APPROVAL_FIELDS = (
    "## Standalone implementation authority",
    "- Parent/spec: intentionally none",
    "- Authority: this issue",
)
STANDALONE_APPROVAL_PATHS = (
    "- Upstream approval: explicit user approval in `/to-tickets`",
    "- Upstream approval: explicit user approval in `/triage`",
)
TRIAGE_COMMENT_DISCLAIMER = "> *This was generated by AI during triage.*"
TRUSTED_APPROVAL_PERMISSIONS = {"write", "admin"}
USER_INVOKED_SKILLS = {
    "code-review", "deep-review", "design-review", "evaluate-model", "grill-me",
    "grill-with-docs", "handoff-doc", "implement", "improve-codebase-architecture",
    "reconcile", "setup-skills", "teach", "to-questionnaire", "to-spec",
    "to-tickets", "triage", "wait-what", "wayfinder", "write-pr",
}
MODEL_INVOKED_SKILLS = {
    "codebase-design", "diagnosing-bugs", "domain-modeling", "grilling",
    "prototype", "research", "resolving-merge-conflicts", "tdd", "wizard",
    "writing-for-agents",
}
# Models and limits the standalone deep-review adapters pinned before the import,
# plus the Claude Code adapter. Claude Code does not confine an agent's Bash to
# the patterns in its tool list, so its read-only roles keep plain Bash.
DEEP_REVIEW_READ_ONLY_TOOLS = ["read", "grep", "glob", "exec"]
DEEP_REVIEW_CLAUDE_READ_ONLY_TOOLS = ["Read", "Grep", "Glob", "Bash"]
DEEP_REVIEW_ROLES = {
    "scout": {
        "codex": {"model": "gpt-6-luna", "model_reasoning_effort": "high", "sandbox_mode": "read-only"},
        "devin": {"model": "gpt-5-6-luna-medium", "allowed-tools": DEEP_REVIEW_READ_ONLY_TOOLS},
        "claude": {"model": "sonnet", "tools": DEEP_REVIEW_CLAUDE_READ_ONLY_TOOLS, "effort": "high"},
    },
    "structural": {
        "codex": {"model": "gpt-6-sol", "model_reasoning_effort": "high", "sandbox_mode": "read-only"},
        "devin": {"model": "gpt-5-6-sol-medium", "allowed-tools": DEEP_REVIEW_READ_ONLY_TOOLS},
        "claude": {"model": "opus", "tools": DEEP_REVIEW_CLAUDE_READ_ONLY_TOOLS, "effort": "high"},
    },
    "validator-static": {
        "codex": {"model": "gpt-6-sol", "model_reasoning_effort": "high", "sandbox_mode": "read-only"},
        "devin": {"model": "gpt-5-6-sol-high", "allowed-tools": DEEP_REVIEW_READ_ONLY_TOOLS},
        "claude": {"model": "opus", "tools": DEEP_REVIEW_CLAUDE_READ_ONLY_TOOLS, "effort": "high"},
    },
    "validator-probe": {
        "codex": {"model": "gpt-6-luna", "model_reasoning_effort": "high", "sandbox_mode": "workspace-write"},
        "devin": {"model": "gpt-5-6-luna-high", "allowed-tools": [*DEEP_REVIEW_READ_ONLY_TOOLS, "write", "edit"]},
        "claude": {"model": "sonnet", "tools": [*DEEP_REVIEW_CLAUDE_READ_ONLY_TOOLS, "Edit", "Write"], "effort": "high"},
    },
}
HARNESS_SPECIFIC_TEXT = re.compile(
    r"Devin|Codex|Claude|run_subagent|spawn_agent|gpt-[0-9]|allowed-tools|sandbox_mode|model_reasoning_effort|\.config/devin|\.codex",
    re.IGNORECASE,
)


class CheckFailure(RuntimeError):
    pass


def fail(message: str) -> None:
    raise CheckFailure(message)


def parse_frontmatter(path: Path) -> tuple[dict[str, str], str]:
    text = path.read_text(encoding="utf-8")
    lines = text.splitlines()
    if not lines or lines[0] != "---":
        fail(f"{path.relative_to(ROOT)}: missing opening frontmatter delimiter")
    try:
        end = lines.index("---", 1)
    except ValueError:
        fail(f"{path.relative_to(ROOT)}: missing closing frontmatter delimiter")

    fields: dict[str, str] = {}
    current_list: str | None = None
    for number, line in enumerate(lines[1:end], start=2):
        if not line.strip() or line.lstrip().startswith("#"):
            continue
        if line.startswith("  - "):
            if current_list is None:
                fail(f"{path.relative_to(ROOT)}:{number}: list item has no key")
            fields[current_list] += "\n" + line[4:].strip()
            continue
        if line.startswith((" ", "\t")) or ":" not in line:
            fail(f"{path.relative_to(ROOT)}:{number}: unsupported or invalid frontmatter")
        key, value = line.split(":", 1)
        key = key.strip()
        value = value.strip()
        if not re.fullmatch(r"[a-z][a-z0-9-]*", key):
            fail(f"{path.relative_to(ROOT)}:{number}: invalid frontmatter key {key!r}")
        if key in fields:
            fail(f"{path.relative_to(ROOT)}:{number}: duplicate frontmatter key {key!r}")
        if value and not (value.startswith(('"', "'")) and value.endswith(('"', "'"))) and ": " in value:
            fail(f"{path.relative_to(ROOT)}:{number}: quote scalar values containing ': '")
        fields[key] = value
        current_list = key if not value else None
    return fields, "\n".join(lines[1:end])


def skill_directories() -> list[Path]:
    stable = [path for path in SKILLS.iterdir() if path.is_dir() and path.name != "experimental"]
    experimental_root = SKILLS / "experimental"
    experimental = [path for path in experimental_root.iterdir() if path.is_dir()]
    return sorted(stable + experimental, key=lambda path: path.as_posix())


def codex_implicit_policy_values(metadata_text: str, metadata: Path) -> list[str]:
    """Read the supported policy field without treating an unrelated key as policy."""
    section = None
    values = []
    for line in metadata_text.splitlines():
        if not line.strip() or line.lstrip().startswith("#"):
            continue
        if not line[0].isspace():
            section = line.split(":", 1)[0]
        if "allow_implicit_invocation" not in line:
            continue
        match = re.fullmatch(r"  allow_implicit_invocation:\s*(true|false)\s*", line)
        if section != "policy" or match is None:
            fail(f"{metadata.relative_to(ROOT)}: allow_implicit_invocation must be a boolean under policy")
        values.append(match.group(1))
    return values


def validate_layout_and_skills() -> list[str]:
    if not (SKILLS / "experimental").is_dir():
        fail("skills/experimental must exist")
    present_retired = sorted(name for name in RETIRED_BUCKETS if (SKILLS / name).exists())
    if present_retired:
        fail(f"retired skill buckets remain: {', '.join(present_retired)}")

    names: dict[str, Path] = {}
    if USER_INVOKED_SKILLS & MODEL_INVOKED_SKILLS:
        fail("stable skill invocation classifications overlap")
    for directory in skill_directories():
        skill_file = directory / "SKILL.md"
        if not skill_file.is_file():
            fail(f"{directory.relative_to(ROOT)}: skill directory lacks SKILL.md")
        wrappers = sorted(path for path in directory.rglob("SKILL.md") if path != skill_file)
        if wrappers:
            fail(f"{wrappers[0].relative_to(ROOT).as_posix()}: a skill has exactly one authoritative SKILL.md")
        fields, raw_frontmatter = parse_frontmatter(skill_file)
        for required in ("name", "description"):
            if not fields.get(required):
                fail(f"{skill_file.relative_to(ROOT)}: missing required {required!r} frontmatter")
        name = fields["name"].strip('"\'')
        if name != directory.name:
            fail(f"{skill_file.relative_to(ROOT)}: name {name!r} does not match directory {directory.name!r}")
        if not re.fullmatch(r"[a-z0-9]+(?:-[a-z0-9]+)*", name):
            fail(f"{skill_file.relative_to(ROOT)}: invalid skill name {name!r}")
        if name in names:
            fail(f"duplicate skill name {name!r}: {names[name]} and {directory}")
        names[name] = directory

        metadata = directory / "agents" / "openai.yaml"
        if not metadata.is_file():
            fail(f"{directory.relative_to(ROOT)}: missing agents/openai.yaml")
        metadata_text = metadata.read_text(encoding="utf-8")
        for required_metadata in ("display_name", "short_description"):
            if not re.search(rf"(?m)^\s*{required_metadata}:\s*\S", metadata_text):
                fail(f"{metadata.relative_to(ROOT)}: missing {required_metadata}")
        if directory.parent == SKILLS:
            expected = "user" if name in USER_INVOKED_SKILLS else "model" if name in MODEL_INVOKED_SKILLS else None
            if expected is None:
                fail(f"{directory.relative_to(ROOT)}: stable skill has no reviewed invocation classification")
            triggers = [trigger for trigger in fields["triggers"].splitlines() if trigger] if "triggers" in fields else None
            expected_triggers = ["user"] if expected == "user" else None
            if triggers != expected_triggers:
                requirement = "must be ['user']" if expected == "user" else "must be omitted to use the default [user, model]"
                fail(f"{skill_file.relative_to(ROOT)}: Devin triggers {requirement}")
            disabled = fields.get("disable-model-invocation")
            if disabled != ("true" if expected == "user" else None):
                fail(f"{skill_file.relative_to(ROOT)}: Claude model invocation disagrees with {expected} classification")
            if "user-invocable" in fields:
                fail(f"{skill_file.relative_to(ROOT)}: Claude user-invocable must be omitted")
            implicit = codex_implicit_policy_values(metadata_text, metadata)
            expected_implicit = ["false"] if expected == "user" else []
            if implicit != expected_implicit:
                fail(f"{metadata.relative_to(ROOT)}: Codex policy disagrees with {expected} classification")
        else:
            implicit_false = bool(re.search(r"(?m)^\s*allow_implicit_invocation:\s*false\s*$", metadata_text))
            disabled = bool(re.search(r"(?m)^disable-model-invocation:\s*true\s*$", raw_frontmatter))
            if disabled != implicit_false:
                fail(f"{directory.relative_to(ROOT)}: SKILL.md and agents/openai.yaml invocation policies disagree")
    actual_stable = {path.name for path in SKILLS.iterdir() if path.is_dir() and path.name != "experimental"}
    if actual_stable != USER_INVOKED_SKILLS | MODEL_INVOKED_SKILLS:
        fail("reviewed invocation classifications do not match stable skill directories")
    return sorted(names)


def iter_repository_text() -> list[Path]:
    paths: list[Path] = []
    for path in ROOT.rglob("*"):
        if not path.is_file() or ".git" in path.parts:
            continue
        if path.suffix.lower() in TEXT_SUFFIXES or path.name in {"LICENSE", ".gitignore", ".gitattributes"}:
            paths.append(path)
    return paths


def validate_repository_references(skill_names: list[str]) -> None:
    for relative in RETIRED_FILES:
        if (ROOT / relative).exists():
            fail(f"retired file remains: {relative}")
    for retired_dir in (".claude-plugin", ".changeset"):
        if (ROOT / retired_dir).exists():
            fail(f"retired directory remains: {retired_dir}")

    for path in iter_repository_text():
        relative = path.relative_to(ROOT).as_posix()
        text = path.read_text(encoding="utf-8")
        if chr(0x2014) in text:
            fail(f"{relative}: em dash violates repository style")
        if relative not in INTENTIONAL_STALE_REFERENCE_FILES:
            for label, pattern in STALE_PATTERNS.items():
                match = pattern.search(text)
                if match:
                    line = text.count("\n", 0, match.start()) + 1
                    fail(f"{relative}:{line}: stale {label} reference")
        if relative not in {"README.md", "scripts/check.py"} and re.search(r"mattpocock/skills", text, re.IGNORECASE):
            fail(f"{relative}: stale upstream repository identity")
        validates_links = path.suffix.lower() == ".md" and (
            path.name == "SKILL.md"
            or path.parent == ROOT
            or relative.startswith(".agents/")
            or relative.startswith(".out-of-scope/")
        )
        if validates_links:
            for match in re.finditer(r"\[[^\]]*\]\(([^)]+)\)", text):
                target = match.group(1).strip().strip("<>").split(maxsplit=1)[0]
                if not target or target.startswith("#") or re.match(r"^[a-z][a-z0-9+.-]*:", target, re.IGNORECASE):
                    continue
                target = urllib.parse.unquote(target.split("#", 1)[0])
                if not (target.startswith(("./", "../")) or "/" in target or Path(target).suffix):
                    continue
                resolved = (path.parent / target).resolve()
                if not resolved.exists():
                    line = text.count("\n", 0, match.start()) + 1
                    fail(f"{relative}:{line}: broken relative link {target!r}")

    readme = (ROOT / "README.md").read_text(encoding="utf-8")
    for name in skill_names:
        expected = f"./skills/{name}/SKILL.md"
        if expected not in readme:
            fail(f"README.md does not link canonical SKILL.md for {name}")


def has_standalone_authority_record(comments: list[dict[str, str]]) -> bool:
    """Recognize complete records written by humans with write-level access."""
    for comment in comments:
        if comment["permission"] not in TRUSTED_APPROVAL_PERMISSIONS or comment["user_type"] != "User":
            continue
        lines = [line.strip() for line in comment["body"].splitlines() if line.strip()]
        valid_records = [
            [*STANDALONE_APPROVAL_FIELDS, STANDALONE_APPROVAL_PATHS[0]],
            [TRIAGE_COMMENT_DISCLAIMER, *STANDALONE_APPROVAL_FIELDS, STANDALONE_APPROVAL_PATHS[1]],
        ]
        if lines in valid_records:
            return True
    return False


def standalone_frontier_numbers(issues: list[dict]) -> list[int]:
    """Project readiness only across explicitly approved parentless issues."""
    ready = []
    for issue in issues:
        if issue["parent"] is not None or not has_standalone_authority_record(issue["comments"]):
            continue
        if issue["state"] != "OPEN" or issue["assignees"] or issue["open_blockers"]:
            continue
        ready.append(issue["number"])
    return sorted(ready)


def resolve_issue_authority(
    *,
    parent: str | None,
    comments: list[dict[str, str]],
    ready_for_agent: bool = False,
) -> str | None:
    """Model authority resolution; readiness does not establish authority."""
    if parent is not None:
        return "parent" if parent == "approved" else None
    if has_standalone_authority_record(comments):
        return "standalone"
    return None


def validate_implementation_authority_contract() -> None:
    tracker = (ROOT / "docs/agents/issue-tracker.md").read_text(encoding="utf-8")
    implement = (ROOT / "skills/implement/SKILL.md").read_text(encoding="utf-8")
    to_tickets = (ROOT / "skills/to-tickets/SKILL.md").read_text(encoding="utf-8")
    triage = (ROOT / "skills/triage/SKILL.md").read_text(encoding="utf-8")
    tracker_seed = (ROOT / "skills/setup-skills/issue-tracker-github.md").read_text(encoding="utf-8")
    reconcile = (ROOT / "skills/reconcile/SKILL.md").read_text(encoding="utf-8")

    required_contract_text = (
        (tracker, "Standalone implementation authority"),
        (tracker, "readiness labels alone do not qualify"),
        (tracker, "author_association"),
        (tracker, "effective repository permission `write` (including `maintain`) or `admin`"),
        (tracker, "do not fall back to standalone authority"),
        (implement, "never fall back to standalone authority"),
        (implement, "verify the approval comment's human account"),
        (to_tickets, "only after the user has approved"),
        (triage, "does not establish standalone implementation authority"),
        (triage, "repository permission of effective `write` (including `maintain`) or `admin`"),
        (tracker_seed, "Standalone implementation authority"),
        (reconcile, "every issue in the repository with no direct or native parent"),
        (reconcile, "standalone frontier in ascending issue-number order"),
    )
    for document, required in required_contract_text:
        if required not in document:
            fail(f"implementation authority contract is missing {required!r}")

    approved_body = "\n".join((*STANDALONE_APPROVAL_FIELDS, STANDALONE_APPROVAL_PATHS[0]))
    triage_body = "\n".join((TRIAGE_COMMENT_DISCLAIMER, *STANDALONE_APPROVAL_FIELDS, STANDALONE_APPROVAL_PATHS[1]))
    owner_comment = {"body": approved_body, "author_association": "OWNER", "permission": "admin", "user_type": "User"}
    member_comment = {"body": approved_body, "author_association": "MEMBER", "permission": "write", "role_name": "maintain", "user_type": "User"}
    collaborator_comment = {"body": approved_body, "author_association": "COLLABORATOR", "permission": "write", "user_type": "User"}
    untrusted_comment = {"body": approved_body, "author_association": "CONTRIBUTOR", "permission": "read", "user_type": "User"}
    bot_comment = {"body": approved_body, "author_association": "OWNER", "permission": "admin", "user_type": "Bot"}
    triage_comment = {"body": triage_body, "author_association": "OWNER", "permission": "write", "user_type": "User"}

    if resolve_issue_authority(parent="approved", comments=[]) != "parent":
        fail("approved parent-backed issue was not accepted")
    if resolve_issue_authority(parent=None, comments=[owner_comment]) != "standalone":
        fail("bounded approved standalone /to-tickets issue without a parent was not accepted")
    if resolve_issue_authority(parent=None, comments=[collaborator_comment]) != "standalone":
        fail("approved standalone authority from a trusted collaborator was not accepted")
    if resolve_issue_authority(parent=None, comments=[member_comment]) != "standalone":
        fail("approved standalone authority from a MEMBER with maintain permission was not accepted")
    if resolve_issue_authority(parent=None, comments=[{**owner_comment, "body": approved_body + "\n- extra: ignored"}]) is not None:
        fail("standalone authority record with unrecognized extra fields was accepted")
    if resolve_issue_authority(parent=None, comments=[]) is not None:
        fail("standalone issue without approval evidence was accepted")
    if resolve_issue_authority(parent=None, comments=[untrusted_comment]) is not None:
        fail("standalone authority record from a read-only commenter was accepted")
    if resolve_issue_authority(parent=None, comments=[{**owner_comment, "permission": "read", "role_name": "triage"}]) is not None:
        fail("standalone authority record from a triage-only commenter was accepted")
    if resolve_issue_authority(parent=None, comments=[bot_comment]) is not None:
        fail("standalone authority record from a bot was accepted")
    if resolve_issue_authority(parent="unapproved", comments=[owner_comment]) is not None:
        fail("issue with unapproved parent fell back to standalone authority")
    if resolve_issue_authority(parent="unresolvable", comments=[owner_comment]) is not None:
        fail("issue with unresolvable parent fell back to standalone authority")
    if resolve_issue_authority(parent=None, comments=[], ready_for_agent=True) is not None:
        fail("ready-for-agent alone granted standalone authority")
    if resolve_issue_authority(parent=None, comments=[triage_comment]) != "standalone":
        fail("explicitly approved standalone /triage issue was not accepted")
    if resolve_issue_authority(parent=None, comments=[{**triage_comment, "body": approved_body.replace(STANDALONE_APPROVAL_PATHS[0], STANDALONE_APPROVAL_PATHS[1])}]) is not None:
        fail("triage approval comment without the required disclaimer was accepted")

    before_close = [
        {"number": 40, "parent": None, "comments": [owner_comment], "state": "OPEN", "assignees": [], "open_blockers": []},
        {"number": 41, "parent": None, "comments": [owner_comment], "state": "OPEN", "assignees": [], "open_blockers": [40]},
        {"number": 42, "parent": "#approved-map", "comments": [], "state": "OPEN", "assignees": [], "open_blockers": []},
        {"number": 43, "parent": None, "comments": [untrusted_comment], "state": "OPEN", "assignees": [], "open_blockers": []},
    ]
    after_close = [
        {**before_close[0], "state": "CLOSED"},
        {**before_close[1], "open_blockers": []},
        *before_close[2:],
    ]
    if standalone_frontier_numbers(before_close) != [40]:
        fail("standalone frontier included a blocked or unauthorized issue before blocker resolution")
    if standalone_frontier_numbers(after_close) != [41]:
        fail("closing a standalone blocker did not promote its approved standalone dependent")


def validate_native_agents() -> None:
    """Generated native reviewer agents must match their role manifests exactly."""
    owners: dict[str, str] = {}
    for skill in generate_agents.agent_skill_directories(ROOT):
        harnesses = sorted(path.name for path in (skill / "harnesses").iterdir() if path.is_dir())
        unsupported = sorted(set(harnesses) - set(generate_agents.HARNESSES))
        if unsupported:
            fail(f"{skill.relative_to(ROOT).as_posix()}/harnesses: unsupported harness directories {', '.join(unsupported)}")
        problems = generate_agents.stale_agents(skill)
        if problems:
            fail("; ".join(problems) + "; run python scripts/generate_agents.py")
        for role in generate_agents.load_roles(skill):
            if role.agent_name in owners:
                fail(f"agent name {role.agent_name!r} is shipped by both {owners[role.agent_name]} and {skill.name}")
            owners[role.agent_name] = skill.name
            codex_file = skill / "harnesses" / "codex" / f"{role.agent_name}.toml"
            if codex_file.is_file():
                parsed = tomllib.loads(codex_file.read_text(encoding="utf-8"))
                if parsed.get("name") != role.agent_name or parsed.get("developer_instructions") != role.body:
                    fail(f"{codex_file.relative_to(ROOT).as_posix()}: generated Codex agent does not round-trip its name and body")
    if "agent-skill" not in owners.values():
        fail("tests/fixtures/agent-skill must ship native reviewer agents")


def deep_review_shared_sources(skill: Path) -> list[Path]:
    """The harness-neutral protocol, glossary, references, and reviewer contracts."""
    return sorted([
        skill / "protocol.md",
        skill / "GLOSSARY.md",
        *(path for path in (skill / "references").rglob("*") if path.is_file()),
        *(path for path in (skill / "reviewers").rglob("*") if path.is_file()),
    ])


def validate_deep_review() -> None:
    """Deep review keeps one harness-neutral copy of its sources and its pinned role limits."""
    skill = SKILLS / "deep-review"
    roles = {role.name: role for role in generate_agents.load_roles(skill)}
    if set(roles) != set(DEEP_REVIEW_ROLES):
        fail(f"deep-review roles must be exactly {', '.join(sorted(DEEP_REVIEW_ROLES))}")
    for name, expected in DEEP_REVIEW_ROLES.items():
        if roles[name].harnesses != expected:
            fail(f"deep-review role {name!r} drifted from its pinned harness models and limits")
    if "# Structural Lens" not in roles["structural"].body or "# Structural Lens" in roles["scout"].body:
        fail("only the deep-review structural scout embeds the structural lens")

    shared = deep_review_shared_sources(skill)
    for path in shared:
        match = HARNESS_SPECIFIC_TEXT.search(path.read_text(encoding="utf-8"))
        if match:
            fail(f"{path.relative_to(ROOT).as_posix()}: harness-specific text {match.group(0)!r} in shared deep-review content")
    scenario_lists = {
        "protocol.md": r"(?m)^- ([^:\n]+): whether ",
        "references/output-template.md": r"(?m)^\| ([^|\n]+?) \| PASS / FAIL / NOT EXERCISED \|",
        "runtime-acceptance.md": r"(?m)^\| ([^|\n]+?) \| [^\n]* \| Same \|$",
    }
    scenarios = {
        relative: [name.strip().lower() for name in re.findall(pattern, (skill / relative).read_text(encoding="utf-8"))]
        for relative, pattern in scenario_lists.items()
    }
    expected_scenarios = scenarios["references/output-template.md"]
    for relative, found in scenarios.items():
        if not found or found != expected_scenarios:
            fail(f"skills/deep-review/{relative}: runtime acceptance scenarios differ from references/output-template.md")

    contents = {path.read_text(encoding="utf-8"): path for path in shared}
    generated = skill / "harnesses"
    for path in iter_repository_text():
        if path in shared or path.is_relative_to(generated):
            continue
        original = contents.get(path.read_text(encoding="utf-8"))
        if original is not None:
            fail(f"{path.relative_to(ROOT).as_posix()}: duplicate copy of {original.relative_to(ROOT).as_posix()}")


def validate_agent_generation_contract() -> None:
    """Prove the freshness check rejects stale, missing, and hand-edited files."""
    source = ROOT / "tests" / "fixtures" / "agent-skill"
    with tempfile.TemporaryDirectory(prefix="skills-agents-") as temp_value:
        skill = Path(temp_value) / "agent-skill"
        shutil.copytree(source, skill)
        expected_files = {
            "harnesses/codex/agent-skill-scout.toml",
            "harnesses/devin/agent-skill-scout/AGENT.md",
            "harnesses/claude/agent-skill-scout.md",
        }
        if not expected_files <= set(generate_agents.render_agents(skill)):
            fail("agent generation does not produce one shared agent name per role for every harness")
        if generate_agents.stale_agents(skill):
            fail("committed fixture agents are not fresh")

        codex_scout = skill / "harnesses" / "codex" / "agent-skill-scout.toml"
        cases = {
            "stale": lambda: (skill / "reviewers" / "reviewer.md").write_text("changed body\n", encoding="utf-8"),
            "missing": lambda: (skill / "harnesses" / "claude" / "agent-skill-probe.md").unlink(),
            "hand-edited": lambda: codex_scout.write_text(codex_scout.read_text(encoding="utf-8") + "# edited\n", encoding="utf-8"),
            "unexpected": lambda: (skill / "harnesses" / "claude" / "agent-skill-extra.md").write_text("extra\n", encoding="utf-8"),
            "malformed": lambda: (skill / "harnesses" / "roles.toml").write_text("[roles.scout]\nbody = 3\n", encoding="utf-8"),
        }
        for label, mutate in cases.items():
            shutil.rmtree(skill)
            shutil.copytree(source, skill)
            mutate()
            if not generate_agents.stale_agents(skill):
                fail(f"agent freshness check accepted a {label} generated agent file")
            if label != "malformed":
                generate_agents.write_agents(skill)
                if generate_agents.stale_agents(skill):
                    fail(f"regeneration did not repair a {label} generated agent file")

        manifest = (source / "harnesses" / "roles.toml").read_text(encoding="utf-8")
        for harness, fields in generate_agents.HARNESS_FIELDS.items():
            for field in fields:
                (skill / "harnesses" / "roles.toml").write_text(
                    without_manifest_field(manifest, f"roles.scout.{harness}", field), encoding="utf-8"
                )
                try:
                    generate_agents.load_roles(skill)
                except generate_agents.AgentManifestError:
                    continue
                fail(f"role manifest accepted a {harness} role without {field!r}")


def without_manifest_field(manifest: str, table: str, field: str) -> str:
    """Drop one key from one table of a role manifest, failing if it is absent."""
    kept, section, removed = [], None, False
    for line in manifest.splitlines(keepends=True):
        stripped = line.strip()
        if stripped.startswith("[") and stripped.endswith("]"):
            section = stripped[1:-1]
        elif section == table and stripped.split("=", 1)[0].strip() == field:
            removed = True
            continue
        kept.append(line)
    if not removed:
        fail(f"test skill manifest has no {field!r} in [{table}]")
    return "".join(kept)


def main() -> int:
    try:
        skill_names = validate_layout_and_skills()
        validate_repository_references(skill_names)
        validate_implementation_authority_contract()
        validate_native_agents()
        validate_deep_review()
        validate_agent_generation_contract()
    except CheckFailure as error:
        print(f"FAIL: {error}", file=sys.stderr)
        return 1
    print(f"Repository checks passed for {len(skill_names)} skills.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
